import {theme as appTheme} from "../../styles/theme.ts";

export const theme = {
    token: {
        colorText: appTheme.colors.textPrimary,
        colorPrimary: appTheme.colors.primary,
        fontFamily: "'Manrope', system-ui, sans-serif",
    },
    components: {
        Dropdown: {
            colorText: appTheme.colors.textPrimary,
            colorTextHover: appTheme.colors.textInverse,
            colorBgElevated: appTheme.colors.surface,
            controlItemBgHover: appTheme.colors.primary,
            controlItemBgActive: appTheme.colors.primary,
            controlItemBgActiveHover: appTheme.colors.primaryHover,
            borderRadius: 12,
            borderRadiusLG: 12,
            borderRadiusSM: 8,
            boxShadowSecondary: `0 8px 24px ${appTheme.colors.shadowStrong}`,
            paddingBlock: 10,
            controlPaddingHorizontal: 16,
            fontSize: 15,
            lineHeight: 1.4,
        },
        Button: {
            borderRadius: 999,
            colorBgContainer: 'transparent',
            colorBorder: 'transparent',
            colorText: appTheme.colors.textPrimary,
            defaultColor: appTheme.colors.textPrimary,
            defaultBg: 'transparent',
            defaultBorderColor: 'transparent',
            defaultHoverBg: appTheme.colors.surfaceMutedHover,
            defaultHoverColor: appTheme.colors.primary,
            defaultHoverBorderColor: 'transparent',
            defaultActiveBg: appTheme.colors.surfaceMutedHover,
            defaultActiveColor: appTheme.colors.primary,
            defaultActiveBorderColor: 'transparent',
            paddingInline: 22,
            paddingBlock: 10,
            fontSize: 16,
            fontWeight: 600,
            controlHeight: 44,
        },
    },
};
